# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        MainWindow.setMinimumSize(QtCore.QSize(800, 700))
        MainWindow.setMaximumSize(QtCore.QSize(800, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Vertical layout for the main window
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # Horizontal layout for buttons
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        # Start button
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setMinimumSize(QtCore.QSize(150, 40))
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        
        # Stop button
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setMinimumSize(QtCore.QSize(150, 40))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        
        # Show Camera button
        self.showButton = QtWidgets.QPushButton(self.centralwidget)
        self.showButton.setMinimumSize(QtCore.QSize(150, 40))
        self.showButton.setObjectName("showButton")
        self.horizontalLayout.addWidget(self.showButton)
        
        # Minimize to Tray button
        self.minimizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.minimizeButton.setMinimumSize(QtCore.QSize(150, 40))
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout.addWidget(self.minimizeButton)
        
        self.verticalLayout.addLayout(self.horizontalLayout)
        
        # Label for camera feed
        self.cameraFeedLabel = QtWidgets.QLabel(self.centralwidget)
        self.cameraFeedLabel.setMinimumSize(QtCore.QSize(780, 580))
        self.cameraFeedLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.cameraFeedLabel.setText("")
        self.cameraFeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraFeedLabel.setObjectName("cameraFeedLabel")
        self.verticalLayout.addWidget(self.cameraFeedLabel)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        
        # About action
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuAbout.addAction(self.actionAbout)
        
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Alea-AirCursor"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.showButton.setText(_translate("MainWindow", "Show Camera"))
        self.minimizeButton.setText(_translate("MainWindow", "Minimize"))
        self.menuAbout.setTitle(_translate("MainWindow", "More"))
        self.actionAbout.setText(_translate("MainWindow", "About"))